### ISSUE TITLE
(details) link on panel in properties view has no effect

### ISSUE THREAD

**Issue by benzimmer** [Scrivito/scrivito_elastic_slider_widget#4]
In the properties view of the slider there is a `(details)` link on each panel. When I click it nothing happens.

![screen shot 2016-08-12 at 16 11 20](https://cloud.githubusercontent.com/assets/164417/17625097/9ee5d9d4-60a7-11e6-9c76-28b3a2ed812b.png)

**Comment by gertimon** [comment]
Fixed with ffff3151e779b62db864c2f9799ea12a7af83325
