### ISSUE TITLE
Widget insertion is not possible

### ISSUE THREAD

**Issue by spiderpug** [Scrivito/scrivito_elastic_slider_widget#5]
The last commit breaks the widget: https://github.com/Scrivito/scrivito_elastic_slider_widget/commit/4bbc5fefc2c23953fae3ccca08930c30c046f42b

Inserting the widget causes an internal server error: `undefined method binary for nil`, as no image is chosen yet.

**Comment by gertimon** [comment]
Thanks for mentioning. Is fixed.
